I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script/map.rpy", line 19, in script
    if classroom_visits == 0:
  File "game/script/map.rpy", line 19, in <module>
    if classroom_visits == 0:
NameError: name 'classroom_visits' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script/map.rpy", line 19, in script
    if classroom_visits == 0:
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\ast.py", line 1762, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\evans\Documents\renpy-7.1.3-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script/map.rpy", line 19, in <module>
    if classroom_visits == 0:
NameError: name 'classroom_visits' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
Break: The Rematch v0.1-alpha
Mon Dec 24 23:47:45 2018
